#!/usr/bin/env ruby

require 'minruby'
require 'colorize'

SKIP_FILES = %w[test1-4.rb test1-5.rb]

Dir.glob('test*.rb').sort.each do |f|
  next if SKIP_FILES.include?(f)

  correct = `ruby #{f}`
  js = `ruby transpile.rb #{f}`
  output = `node -e '#{js}'`

  print "#{f} => "
  if output == correct
    puts 'OK!'.green
  else
    puts 'NG!'.red
    puts js
    exit(1)
  end
end
